In [1]:
import numpy as numpy
import csv
from sklearn.neighbors import KNeighborsClassifier
import pandas
from sklearn.preprocessing import StandardScaler

file_name = 'student-mat-nograde3.csv'

data_frame = pandas.read_csv(file_name)
data_frame = pandas.get_dummies(data_frame)
print(data_frame)
numpy_array = data_frame.values

#using scaler
scaler = StandardScaler()
scaler.fit(numpy_array)
numpy_array = scaler.transform(numpy_array)

print(numpy_array)

file_name = 'student-math.csv'
one_row = []
raw_data = open(file_name, 'rt')

with open(file_name) as f:
    reader = csv.reader(raw_data, delimiter=',')
    next(reader)
    data_y = []
    for i, row in enumerate(reader):
        if int(row[len(row) - 1]) > 15:
            data_y.append(1)
        else:
            data_y.append(0)
        #data_y.append(row[len(row) - 1])
    y = list(data_y)
    data_y = numpy.array(y).astype('int')

neigh = KNeighborsClassifier(n_neighbors=4)
print(data_y)
print(data_y.shape)
neigh.fit(numpy_array, data_y)
print(data_y)
print(neigh.score(numpy_array, data_y))

     age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  \
0     18     4     4           2          2         0       4         3
1     17     1     1           1          2         0       5         3
2     15     1     1           1          2         3       4         3
3     15     4     2           1          3         0       3         2
4     16     3     3           1          2         0       4         3
5     16     4     3           1          2         0       5         4
6     16     2     2           1          2         0       4         4
7     17     4     4           2          2         0       4         1
8     15     3     2           1          2         0       4         2
9     15     3     4           1          2         0       5         5
10    15     4     4           1          2         0       3         3
11    15     2     1           3          3         0       5         2
12    15     4     4           1          1         0       4         3
13    15     4     3           2          2         0       5         4
14    15     2     2           1          3         0       4         5
15    16     4     4           1          1         0       4         4
16    16     4     4           1          3         0       3         2
17    16     3     3           3          2         0       5         3
18    17     3     2           1          1         3       5         5
19    16     4     3           1          1         0       3         1
20    15     4     3           1          2         0       4         4
21    15     4     4           1          1         0       5         4
22    16     4     2           1          2         0       4         5
23    16     2     2           2          2         0       5         4
24    15     2     4           1          3         0       4         3
25    16     2     2           1          1         2       1         2
26    15     2     2           1          1         0       4         2
27    15     4     2           1          1         0       2         2
28    16     3     4           1          2         0       5         3
29    16     4     4           1          2         0       4         4
..   ...   ...   ...         ...        ...       ...     ...       ...
365   18     1     3           2          2         0       3         3
366   18     4     4           2          3         0       4         2
367   17     1     1           3          1         1       5         2
368   18     2     3           2          1         0       5         2
369   18     4     4           3          2         0       3         2
370   19     3     2           2          2         2       3         2
371   18     1     2           3          1         0       4         3
372   17     2     2           1          3         0       3         4
373   17     1     2           1          1         0       3         5
374   18     4     4           2          3         0       5         4
375   18     1     1           4          3         0       4         3
376   20     4     2           2          3         2       5         4
377   18     4     4           1          2         0       5         4
378   18     3     3           1          2         0       4         1
379   17     3     1           1          2         0       4         5
380   18     4     4           1          2         0       3         2
381   18     2     1           2          1         0       4         4
382   17     2     3           2          2         0       4         4
383   19     1     1           2          1         1       4         3
384   18     4     2           2          1         1       5         4
385   18     2     2           2          3         0       5         3
386   18     4     4           3          1         0       4         4
387   19     2     3           1          3         1       5         4
388   18     3     1           1          2         0       4         3
389   18     1     1           2          2         1       1         1
390   20     2     2           1          2         2       5         5
391   17     3     1           2          1         0       2         4
392   21     1     1           1          1         3       5         5
393   18     3     2           3          1         0       4         4
394   19     1     1           1          1         0       3         2

     goout  Dalc      ...       activities_no  activities_yes  nursery_no  \
0        4     1      ...                   1               0           0
1        3     1      ...                   1               0           1
2        2     2      ...                   1               0           0
3        2     1      ...                   0               1           0
4        2     1      ...                   1               0           0
5        2     1      ...                   0               1           0
6        4     1      ...                   1               0           0
7        4     1      ...                   1               0           0
8        2     1      ...                   1               0           0
9        1     1      ...                   0               1           0
10       3     1      ...                   1               0           0
11       2     1      ...                   0               1           0
12       3     1      ...                   0               1           0
13       3     1      ...                   1               0           0
14       2     1      ...                   1               0           0
15       4     1      ...                   1               0           0
16       3     1      ...                   0               1           0
17       2     1      ...                   0               1           0
18       5     2      ...                   0               1           0
19       3     1      ...                   0               1           0
20       1     1      ...                   1               0           0
21       2     1      ...                   1               0           0
22       1     1      ...                   0               1           0
23       4     2      ...                   0               1           0
24       2     1      ...                   0               1           0
25       2     1      ...                   1               0           1
26       2     1      ...                   1               0           0
27       4     2      ...                   1               0           0
28       3     1      ...                   0               1           0
29       5     5      ...                   0               1           0
..     ...   ...      ...                 ...             ...         ...
365      4     2      ...                   1               0           0
366      2     2      ...                   1               0           0
367      1     1      ...                   1               0           0
368      3     1      ...                   1               0           0
369      2     4      ...                   1               0           1
370      2     1      ...                   0               1           0
371      3     2      ...                   0               1           0
372      3     1      ...                   0               1           0
373      5     1      ...                   0               1           0
374      4     1      ...                   1               0           0
375      2     1      ...                   1               0           0
376      3     1      ...                   1               0           1
377      3     3      ...                   0               1           0
378      3     1      ...                   1               0           0
379      4     2      ...                   0               1           1
380      4     1      ...                   0               1           1
381      3     1      ...                   0               1           1
382      3     1      ...                   0               1           0
383      2     1      ...                   1               0           0
384      3     4      ...                   1               0           0
385      3     1      ...                   1               0           0
386      3     2      ...                   0               1           0
387      2     1      ...                   0               1           1
388      4     1      ...                   1               0           0
389      1     1      ...                   0               1           0
390      4     4      ...                   1               0           0
391      5     3      ...                   1               0           1
392      3     3      ...                   1               0           1
393      1     3      ...                   1               0           1
394      3     3      ...                   1               0           0

     nursery_yes  higher_no  higher_yes  internet_no  internet_yes  \
0              1          0           1            1             0
1              0          0           1            0             1
2              1          0           1            0             1
3              1          0           1            0             1
4              1          0           1            1             0
5              1          0           1            0             1
6              1          0           1            0             1
7              1          0           1            1             0
8              1          0           1            0             1
9              1          0           1            0             1
10             1          0           1            0             1
11             1          0           1            0             1
12             1          0           1            0             1
13             1          0           1            0             1
14             1          0           1            0             1
15             1          0           1            0             1
16             1          0           1            0             1
17             1          0           1            1             0
18             1          0           1            0             1
19             1          0           1            0             1
20             1          0           1            0             1
21             1          0           1            0             1
22             1          0           1            0             1
23             1          0           1            0             1
24             1          0           1            0             1
25             0          0           1            0             1
26             1          0           1            0             1
27             1          0           1            0             1
28             1          0           1            0             1
29             1          0           1            0             1
..           ...        ...         ...          ...           ...
365            1          0           1            1             0
366            1          0           1            0             1
367            1          0           1            0             1
368            1          0           1            0             1
369            0          0           1            0             1
370            1          0           1            1             0
371            1          1           0            0             1
372            1          0           1            1             0
373            1          0           1            0             1
374            1          0           1            0             1
375            1          0           1            0             1
376            0          0           1            0             1
377            1          0           1            0             1
378            1          0           1            0             1
379            0          0           1            0             1
380            0          0           1            0             1
381            0          0           1            0             1
382            1          0           1            0             1
383            1          0           1            1             0
384            1          0           1            1             0
385            1          0           1            1             0
386            1          0           1            0             1
387            0          0           1            0             1
388            1          0           1            0             1
389            1          0           1            1             0
390            1          0           1            1             0
391            0          0           1            0             1
392            0          0           1            1             0
393            0          0           1            0             1
394            1          0           1            0             1

     romantic_no  romantic_yes
0              1             0
1              1             0
2              1             0
3              0             1
4              1             0
5              1             0
6              1             0
7              1             0
8              1             0
9              1             0
10             1             0
11             1             0
12             1             0
13             1             0
14             0             1
15             1             0
16             1             0
17             1             0
18             1             0
19             1             0
20             1             0
21             1             0
22             1             0
23             1             0
24             1             0
25             1             0
26             1             0
27             1             0
28             1             0
29             0             1
..           ...           ...
365            1             0
366            0             1
367            0             1
368            0             1
369            0             1
370            0             1
371            0             1
372            0             1
373            1             0
374            1             0
375            1             0
376            0             1
377            1             0
378            0             1
379            1             0
380            1             0
381            0             1
382            1             0
383            1             0
384            1             0
385            1             0
386            0             1
387            1             0
388            1             0
389            1             0
390            1             0
391            1             0
392            1             0
393            1             0
394            1             0

[395 rows x 58 columns]
[[ 1.02304645  1.14385567  1.36037064 ... -2.23267743  0.70844982
  -0.70844982]
 [ 0.23837976 -1.60000865 -1.39997047 ...  0.44789274  0.70844982
  -0.70844982]
 [-1.33095364 -1.60000865 -1.39997047 ...  0.44789274  0.70844982
  -0.70844982]
 ...
 [ 3.37704655 -1.60000865 -1.39997047 ... -2.23267743  0.70844982
  -0.70844982]
 [ 1.02304645  0.22923423 -0.47985677 ...  0.44789274  0.70844982
  -0.70844982]
 [ 1.80771315 -1.60000865 -1.39997047 ...  0.44789274  0.70844982
  -0.70844982]]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1
 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 1
 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0
 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
(395,)
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1
 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 1
 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0
 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
0.9189873417721519

C:\Users\Erik Van\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

In [2]:
import numpy as numpy
import csv
from sklearn.neighbors import KNeighborsClassifier
import pandas
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

file_name = 'student-mat-nograde3.csv'

data_frame = pandas.read_csv(file_name)
data_frame = pandas.get_dummies(data_frame)
print(data_frame)
#raw_data = open(file_name, 'rt')
numpy_array = data_frame.values

#using scaler
scaler = StandardScaler()
scaler.fit(numpy_array)
numpy_array = scaler.transform(numpy_array)

print(numpy_array)

file_name = 'student-math.csv'
one_row = []
raw_data = open(file_name, 'rt')

with open(file_name) as f:
    reader = csv.reader(raw_data, delimiter=',')
    next(reader)
    data_y = []
    for i, row in enumerate(reader):
        if int(row[len(row) - 1]) > 15:
            data_y.append(1)
        else:
            data_y.append(0)
        #data_y.append(row[len(row) - 1])
    y = list(data_y)
    data_y = numpy.array(y).astype('int')

classifier = SVC(gamma='auto')
classifier.fit(numpy_array, data_y) 
print(classifier.score(numpy_array, data_y))

     age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  \
0     18     4     4           2          2         0       4         3
1     17     1     1           1          2         0       5         3
2     15     1     1           1          2         3       4         3
3     15     4     2           1          3         0       3         2
4     16     3     3           1          2         0       4         3
5     16     4     3           1          2         0       5         4
6     16     2     2           1          2         0       4         4
7     17     4     4           2          2         0       4         1
8     15     3     2           1          2         0       4         2
9     15     3     4           1          2         0       5         5
10    15     4     4           1          2         0       3         3
11    15     2     1           3          3         0       5         2
12    15     4     4           1          1         0       4         3
13    15     4     3           2          2         0       5         4
14    15     2     2           1          3         0       4         5
15    16     4     4           1          1         0       4         4
16    16     4     4           1          3         0       3         2
17    16     3     3           3          2         0       5         3
18    17     3     2           1          1         3       5         5
19    16     4     3           1          1         0       3         1
20    15     4     3           1          2         0       4         4
21    15     4     4           1          1         0       5         4
22    16     4     2           1          2         0       4         5
23    16     2     2           2          2         0       5         4
24    15     2     4           1          3         0       4         3
25    16     2     2           1          1         2       1         2
26    15     2     2           1          1         0       4         2
27    15     4     2           1          1         0       2         2
28    16     3     4           1          2         0       5         3
29    16     4     4           1          2         0       4         4
..   ...   ...   ...         ...        ...       ...     ...       ...
365   18     1     3           2          2         0       3         3
366   18     4     4           2          3         0       4         2
367   17     1     1           3          1         1       5         2
368   18     2     3           2          1         0       5         2
369   18     4     4           3          2         0       3         2
370   19     3     2           2          2         2       3         2
371   18     1     2           3          1         0       4         3
372   17     2     2           1          3         0       3         4
373   17     1     2           1          1         0       3         5
374   18     4     4           2          3         0       5         4
375   18     1     1           4          3         0       4         3
376   20     4     2           2          3         2       5         4
377   18     4     4           1          2         0       5         4
378   18     3     3           1          2         0       4         1
379   17     3     1           1          2         0       4         5
380   18     4     4           1          2         0       3         2
381   18     2     1           2          1         0       4         4
382   17     2     3           2          2         0       4         4
383   19     1     1           2          1         1       4         3
384   18     4     2           2          1         1       5         4
385   18     2     2           2          3         0       5         3
386   18     4     4           3          1         0       4         4
387   19     2     3           1          3         1       5         4
388   18     3     1           1          2         0       4         3
389   18     1     1           2          2         1       1         1
390   20     2     2           1          2         2       5         5
391   17     3     1           2          1         0       2         4
392   21     1     1           1          1         3       5         5
393   18     3     2           3          1         0       4         4
394   19     1     1           1          1         0       3         2

     goout  Dalc      ...       activities_no  activities_yes  nursery_no  \
0        4     1      ...                   1               0           0
1        3     1      ...                   1               0           1
2        2     2      ...                   1               0           0
3        2     1      ...                   0               1           0
4        2     1      ...                   1               0           0
5        2     1      ...                   0               1           0
6        4     1      ...                   1               0           0
7        4     1      ...                   1               0           0
8        2     1      ...                   1               0           0
9        1     1      ...                   0               1           0
10       3     1      ...                   1               0           0
11       2     1      ...                   0               1           0
12       3     1      ...                   0               1           0
13       3     1      ...                   1               0           0
14       2     1      ...                   1               0           0
15       4     1      ...                   1               0           0
16       3     1      ...                   0               1           0
17       2     1      ...                   0               1           0
18       5     2      ...                   0               1           0
19       3     1      ...                   0               1           0
20       1     1      ...                   1               0           0
21       2     1      ...                   1               0           0
22       1     1      ...                   0               1           0
23       4     2      ...                   0               1           0
24       2     1      ...                   0               1           0
25       2     1      ...                   1               0           1
26       2     1      ...                   1               0           0
27       4     2      ...                   1               0           0
28       3     1      ...                   0               1           0
29       5     5      ...                   0               1           0
..     ...   ...      ...                 ...             ...         ...
365      4     2      ...                   1               0           0
366      2     2      ...                   1               0           0
367      1     1      ...                   1               0           0
368      3     1      ...                   1               0           0
369      2     4      ...                   1               0           1
370      2     1      ...                   0               1           0
371      3     2      ...                   0               1           0
372      3     1      ...                   0               1           0
373      5     1      ...                   0               1           0
374      4     1      ...                   1               0           0
375      2     1      ...                   1               0           0
376      3     1      ...                   1               0           1
377      3     3      ...                   0               1           0
378      3     1      ...                   1               0           0
379      4     2      ...                   0               1           1
380      4     1      ...                   0               1           1
381      3     1      ...                   0               1           1
382      3     1      ...                   0               1           0
383      2     1      ...                   1               0           0
384      3     4      ...                   1               0           0
385      3     1      ...                   1               0           0
386      3     2      ...                   0               1           0
387      2     1      ...                   0               1           1
388      4     1      ...                   1               0           0
389      1     1      ...                   0               1           0
390      4     4      ...                   1               0           0
391      5     3      ...                   1               0           1
392      3     3      ...                   1               0           1
393      1     3      ...                   1               0           1
394      3     3      ...                   1               0           0

     nursery_yes  higher_no  higher_yes  internet_no  internet_yes  \
0              1          0           1            1             0
1              0          0           1            0             1
2              1          0           1            0             1
3              1          0           1            0             1
4              1          0           1            1             0
5              1          0           1            0             1
6              1          0           1            0             1
7              1          0           1            1             0
8              1          0           1            0             1
9              1          0           1            0             1
10             1          0           1            0             1
11             1          0           1            0             1
12             1          0           1            0             1
13             1          0           1            0             1
14             1          0           1            0             1
15             1          0           1            0             1
16             1          0           1            0             1
17             1          0           1            1             0
18             1          0           1            0             1
19             1          0           1            0             1
20             1          0           1            0             1
21             1          0           1            0             1
22             1          0           1            0             1
23             1          0           1            0             1
24             1          0           1            0             1
25             0          0           1            0             1
26             1          0           1            0             1
27             1          0           1            0             1
28             1          0           1            0             1
29             1          0           1            0             1
..           ...        ...         ...          ...           ...
365            1          0           1            1             0
366            1          0           1            0             1
367            1          0           1            0             1
368            1          0           1            0             1
369            0          0           1            0             1
370            1          0           1            1             0
371            1          1           0            0             1
372            1          0           1            1             0
373            1          0           1            0             1
374            1          0           1            0             1
375            1          0           1            0             1
376            0          0           1            0             1
377            1          0           1            0             1
378            1          0           1            0             1
379            0          0           1            0             1
380            0          0           1            0             1
381            0          0           1            0             1
382            1          0           1            0             1
383            1          0           1            1             0
384            1          0           1            1             0
385            1          0           1            1             0
386            1          0           1            0             1
387            0          0           1            0             1
388            1          0           1            0             1
389            1          0           1            1             0
390            1          0           1            1             0
391            0          0           1            0             1
392            0          0           1            1             0
393            0          0           1            0             1
394            1          0           1            0             1

     romantic_no  romantic_yes
0              1             0
1              1             0
2              1             0
3              0             1
4              1             0
5              1             0
6              1             0
7              1             0
8              1             0
9              1             0
10             1             0
11             1             0
12             1             0
13             1             0
14             0             1
15             1             0
16             1             0
17             1             0
18             1             0
19             1             0
20             1             0
21             1             0
22             1             0
23             1             0
24             1             0
25             1             0
26             1             0
27             1             0
28             1             0
29             0             1
..           ...           ...
365            1             0
366            0             1
367            0             1
368            0             1
369            0             1
370            0             1
371            0             1
372            0             1
373            1             0
374            1             0
375            1             0
376            0             1
377            1             0
378            0             1
379            1             0
380            1             0
381            0             1
382            1             0
383            1             0
384            1             0
385            1             0
386            0             1
387            1             0
388            1             0
389            1             0
390            1             0
391            1             0
392            1             0
393            1             0
394            1             0

[395 rows x 58 columns]
[[ 1.02304645  1.14385567  1.36037064 ... -2.23267743  0.70844982
  -0.70844982]
 [ 0.23837976 -1.60000865 -1.39997047 ...  0.44789274  0.70844982
  -0.70844982]
 [-1.33095364 -1.60000865 -1.39997047 ...  0.44789274  0.70844982
  -0.70844982]
 ...
 [ 3.37704655 -1.60000865 -1.39997047 ... -2.23267743  0.70844982
  -0.70844982]
 [ 1.02304645  0.22923423 -0.47985677 ...  0.44789274  0.70844982
  -0.70844982]
 [ 1.80771315 -1.60000865 -1.39997047 ...  0.44789274  0.70844982
  -0.70844982]]
0.959493670886076

C:\Users\Erik Van\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)